#pragma once

#include <string>

namespace aid { namespace xodr {

class XodrMap;

/**
 * @brief The base class for error messages generated by the link validation functions.
 */
class LinkValidationError
{
  public:
    virtual ~LinkValidationError() = default;

    /**
     * @brief Provides a human readable description of this error
     *
     * @param map           The XodrMap to which this error applies.
     * @return              The error message.
     */
    virtual std::string description(const XodrMap& map) const = 0;
};

}}  // namespace aid::xodr